spring.application.name=inkavoice
# Puerto del servidor
server.port=3000

# Base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/inkavoice_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Root2003
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# URLs de integración
inkavoice.ai.backend.url=http://localhost:8000
google.client.id=480616576404-dlbkn2qens5mt2l4es5ibmsr0rri7lt5.apps.googleusercontent.com

# Seguridad JWT (Clave de 256 bits en Base64)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Límite de tamaño para subir archivos (Fotos y Audios)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB